/**
 * Integration tests for `catalyst init`
 *
 * Runs the built CLI against a temporary git repo seeded with command files
 * generated by earlier Catalyst versions, and verifies the AI plugin install
 * workflow cleans them up without touching user files.
 */

import { execSync } from "child_process";
import * as path from "path";
import * as fs from "fs";
import * as os from "os";

const ROOT_DIR = path.join(__dirname, "../../..");
const DIST_DIR = path.join(ROOT_DIR, "dist");
// Use the built bin/ shim so the CLI loads from dist/cli/ (compiled JS),
// not src/cli/ (TS with @core/... path aliases that tsx can't resolve
// from a cwd outside the repo).
const CLI_PATH = path.join(DIST_DIR, "bin", "catalyst.js");

// Tests exercise the CLI from a separate cwd, which requires the package to
// be available at node_modules/@xerilium/catalyst (path-resolver maps
// `catalyst://` to that location) and a built dist/.
const distExists = fs.existsSync(DIST_DIR);
const conditionalDescribe = distExists ? describe : describe.skip;

const CATALYST_SECTION = "# Catalyst commands\n";

function runInit(cwd: string): {
  stdout: string;
  stderr: string;
  exitCode: number;
} {
  try {
    const stdout = execSync(`node ${CLI_PATH} init`, {
      encoding: "utf-8",
      cwd,
      env: { ...process.env, NO_COLOR: "1" },
      maxBuffer: 10 * 1024 * 1024,
    });
    return { stdout, stderr: "", exitCode: 0 };
  } catch (error: unknown) {
    const e = error as { stdout?: string; stderr?: string; status?: number };
    return {
      stdout: e.stdout || "",
      stderr: e.stderr || "",
      exitCode: e.status || 1,
    };
  }
}

function setupTmpRepo(): string {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "catalyst-init-"));
  execSync("git init -q", { cwd: tmpDir });
  // Symlink node_modules/@xerilium/catalyst → dist/ so `catalyst://` resolves
  // to the built package (matching real consumer install layout).
  fs.mkdirSync(path.join(tmpDir, "node_modules", "@xerilium"), {
    recursive: true,
  });
  fs.symlinkSync(
    DIST_DIR,
    path.join(tmpDir, "node_modules", "@xerilium", "catalyst"),
    "dir",
  );
  return tmpDir;
}

function write(root: string, rel: string, content: string): void {
  const p = path.join(root, rel);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content);
}

/** Seed the layout written by the retired per-provider command generator. */
function seedLegacyCommands(root: string): void {
  for (const dir of [".claude/commands/catalyst", ".cursor/commands/catalyst"]) {
    write(root, `${dir}/create.md`, "---\nname: create\n---\n# create\n");
    write(root, `${dir}/old-command.md`, "# removed in a later version\n");
    write(root, `${dir}/.gitignore`, `${CATALYST_SECTION}*\n`);
  }
  write(root, ".github/prompts/catalyst.create.prompt.md", "# create\n");
  write(root, ".github/prompts/catalyst.pr-review.prompt.md", "# pr-review\n");
  write(
    root,
    ".github/prompts/.gitignore",
    `${CATALYST_SECTION}.gitignore\ncatalyst.*.prompt.md\n`,
  );
}

/** Snapshot every file under the legacy command locations. */
function snapshot(root: string): Record<string, string> {
  const result: Record<string, string> = {};
  const walk = (dir: string) => {
    if (!fs.existsSync(dir)) return;
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else result[path.relative(root, p)] = fs.readFileSync(p, "utf8");
    }
  };
  for (const rel of [".claude", ".cursor", ".github"]) walk(path.join(root, rel));
  return result;
}

conditionalDescribe("catalyst init", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = setupTmpRepo();
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  describe("clean project", () => {
    /**
     * @req FR:cli-init/init.@command
     * @req FR:cli-init/init.@playbook
     * @req FR:cli-init/init.ai-plugin
     * @req FR:ai-plugin/install.@playbook
     * @req FR:ai-plugin/install.input
     */
    it("exits successfully without writing AI command files", () => {
      const result = runInit(tmpDir);
      expect(result.exitCode).toBe(0);
      expect(snapshot(tmpDir)).toEqual({});
    });

    /** @req FR:cli-init/init.handoff */
    it("tells the user to add the plugin and run /catalyst:init", () => {
      const result = runInit(tmpDir);
      expect(result.stdout).toMatch(/plugin/i);
      expect(result.stdout).toContain("/plugin install catalyst@xerilium");
      expect(result.stdout).toContain("/catalyst:init");
    });
  });

  describe("legacy command cleanup", () => {
    /** @req FR:ai-plugin/install.legacy */
    it("deletes generated command files for every retired provider", () => {
      seedLegacyCommands(tmpDir);
      expect(runInit(tmpDir).exitCode).toBe(0);
      const remaining = Object.keys(snapshot(tmpDir));
      expect(remaining.filter((f) => /catalyst/.test(f))).toEqual([]);
    });

    /** @req FR:ai-plugin/install.legacy.gitignore */
    it("removes generated .gitignore files", () => {
      seedLegacyCommands(tmpDir);
      runInit(tmpDir);
      expect(fs.existsSync(path.join(tmpDir, ".claude/commands/catalyst/.gitignore"))).toBe(false);
      expect(fs.existsSync(path.join(tmpDir, ".github/prompts/.gitignore"))).toBe(false);
    });

    /** @req FR:ai-plugin/install.legacy.gitignore */
    it("removes only the Catalyst section from a shared .gitignore", () => {
      seedLegacyCommands(tmpDir);
      write(
        tmpDir,
        ".github/prompts/.gitignore",
        `user-secret.txt\n*.bak\n\n${CATALYST_SECTION}.gitignore\ncatalyst.*.prompt.md\n`,
      );
      runInit(tmpDir);
      const content = fs.readFileSync(path.join(tmpDir, ".github/prompts/.gitignore"), "utf8");
      expect(content).toContain("user-secret.txt");
      expect(content).toContain("*.bak");
      expect(content).not.toContain("catalyst.*.prompt.md");
      expect(content).not.toMatch(/# Catalyst commands/i);
    });

    /** @req FR:ai-plugin/install.legacy.gitignore */
    it("removes the older generated-section header too", () => {
      write(
        tmpDir,
        ".github/prompts/.gitignore",
        "# Generated by Catalyst — do not edit manually\n.gitignore\ncatalyst.*.prompt.md\n",
      );
      runInit(tmpDir);
      expect(fs.existsSync(path.join(tmpDir, ".github/prompts/.gitignore"))).toBe(false);
    });

    /** @req FR:ai-plugin/install.legacy.directories */
    it("removes emptied catalyst command directories", () => {
      seedLegacyCommands(tmpDir);
      runInit(tmpDir);
      expect(fs.existsSync(path.join(tmpDir, ".claude/commands/catalyst"))).toBe(false);
      expect(fs.existsSync(path.join(tmpDir, ".cursor/commands/catalyst"))).toBe(false);
    });

    /** @req FR:ai-plugin/install.preserve */
    it("keeps user files next to generated ones", () => {
      seedLegacyCommands(tmpDir);
      write(tmpDir, ".claude/commands/mine.md", "# mine\n");
      write(tmpDir, ".claude/commands/catalyst/notes.txt", "keep\n");
      write(tmpDir, ".github/prompts/review.prompt.md", "# user prompt\n");
      write(tmpDir, ".github/prompts/catalyst-notes.md", "keep\n");

      runInit(tmpDir);

      expect(Object.keys(snapshot(tmpDir)).sort()).toEqual(
        [
          ".claude/commands/catalyst/notes.txt",
          ".claude/commands/mine.md",
          ".github/prompts/catalyst-notes.md",
          ".github/prompts/review.prompt.md",
        ].sort(),
      );
    });
  });

  describe("idempotency", () => {
    /**
     * @req FR:cli-init/init.idempotent
     * @req FR:ai-plugin/install.idempotent
     */
    it("makes no changes on a second run", () => {
      seedLegacyCommands(tmpDir);
      write(tmpDir, ".github/prompts/.gitignore", "user-secret.txt\n");
      runInit(tmpDir);
      const before = snapshot(tmpDir);
      const second = runInit(tmpDir);
      expect(second.exitCode).toBe(0);
      expect(snapshot(tmpDir)).toEqual(before);
    });
  });
});
