// AUTO-GENERATED - DO NOT EDIT MANUALLY
// Generated by scripts/generate-action-registry.ts
//
// This file is automatically generated at build time from action implementations.
// To update metadata, modify the action class's static properties or config interfaces.

import type { ActionMetadata } from '../types/action-metadata';

/**
 * Auto-generated registry of action metadata
 *
 * Maps action types (kebab-case) to their metadata including:
 * - dependencies: External CLI tools and environment variables required
 * - primaryProperty: Property name for YAML shorthand syntax
 * - configSchema: JSON Schema for action configuration validation
 *
 * Generated at build time by scanning action implementations.
 */
export const ACTION_REGISTRY: Record<string, ActionMetadata> = {
  "script": {
    "configSchema": {
      "description": "Configuration for the script action (JavaScript execution)\n\nExecutes JavaScript code in an isolated VM context with controlled access to:\n- fs module for file operations\n- path module for path manipulation\n- console for logging\n- get() function for accessing playbook variables",
      "type": "object",
      "properties": {
        "code": {
          "description": "JavaScript code to execute\n\nCode is wrapped in an async function and executed in an isolated VM context.\nThe return value becomes the action result value.",
          "type": "string",
          "title": "code"
        },
        "cwd": {
          "description": "Working directory for file operations",
          "default": "Repository root",
          "type": "string",
          "title": "cwd"
        },
        "timeout": {
          "description": "Maximum execution time in milliseconds",
          "default": "30000 (30 seconds)",
          "type": "number",
          "title": "timeout"
        }
      },
      "required": [
        "code"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "powershell": {
    "dependencies": {
      "cli": [
        {
          "name": "pwsh",
          "versionCommand": "pwsh --version",
          "minVersion": "7.0.0",
          "installDocs": "https://github.com/PowerShell/PowerShell#get-powershell"
        }
      ]
    },
    "primaryProperty": "code",
    "configSchema": {
      "description": "Configuration for the powershell action (PowerShell script execution)\n\nExecutes PowerShell scripts using child_process.exec() with pwsh shell.\nRequires PowerShell 7+ (cross-platform).",
      "type": "object",
      "properties": {
        "code": {
          "description": "PowerShell script to execute\n\nScript is executed using pwsh shell via child_process.exec().",
          "type": "string",
          "title": "code"
        },
        "cwd": {
          "description": "Working directory for script execution",
          "default": "Repository root",
          "type": "string",
          "title": "cwd"
        },
        "env": {
          "description": "Environment variables for script execution\n\nThese are merged with process.env, with config values taking precedence.",
          "type": "object",
          "title": "env"
        },
        "timeout": {
          "description": "Maximum execution time in milliseconds",
          "default": "60000 (60 seconds)",
          "type": "number",
          "title": "timeout"
        }
      },
      "required": [
        "code"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "bash": {
    "dependencies": {
      "cli": [
        {
          "name": "bash",
          "versionCommand": "bash --version",
          "platforms": [
            "linux",
            "darwin"
          ],
          "installDocs": "https://www.gnu.org/software/bash/"
        },
        {
          "name": "bash",
          "versionCommand": "bash --version",
          "platforms": [
            "win32"
          ],
          "installDocs": "https://docs.microsoft.com/windows/wsl/install"
        }
      ]
    },
    "primaryProperty": "code",
    "configSchema": {
      "description": "Configuration for the bash action (Bash script execution)\n\nExecutes Bash scripts using child_process.exec() with bash shell.\nAvailable on Unix/Linux/macOS systems.",
      "type": "object",
      "properties": {
        "code": {
          "description": "Bash script to execute\n\nScript is executed using bash shell via child_process.exec().",
          "type": "string",
          "title": "code"
        },
        "cwd": {
          "description": "Working directory for script execution",
          "default": "Repository root",
          "type": "string",
          "title": "cwd"
        },
        "env": {
          "description": "Environment variables for script execution\n\nThese are merged with process.env, with config values taking precedence.",
          "type": "object",
          "title": "env"
        },
        "timeout": {
          "description": "Maximum execution time in milliseconds",
          "default": "60000 (60 seconds)",
          "type": "number",
          "title": "timeout"
        }
      },
      "required": [
        "code"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "put": {
    "configSchema": {
      "description": "Configuration for HTTP actions with request bodies (POST, PUT, PATCH)",
      "type": "object",
      "properties": {
        "body": {
          "description": "Request payload as string or object (optional)",
          "type": [
            "string",
            "object"
          ],
          "title": "body"
        },
        "contentType": {
          "description": "Content-Type header override (default: 'application/json' if body is object, 'text/plain' if string)",
          "type": "string",
          "title": "contentType"
        },
        "url": {
          "description": "Target endpoint URL (supports template interpolation)",
          "type": "string",
          "title": "url"
        },
        "headers": {
          "description": "Request headers as key-value pairs (optional)",
          "type": "object",
          "title": "headers"
        },
        "timeout": {
          "description": "Request timeout in milliseconds (default: 30000)",
          "type": "number",
          "title": "timeout"
        },
        "retries": {
          "description": "Number of retry attempts on failure (default: 3)",
          "type": "number",
          "title": "retries"
        },
        "validateStatus": {
          "description": "Function to validate response status codes (default: status >= 200 && status < 300)",
          "type": "object",
          "title": "validateStatus"
        }
      },
      "required": [
        "url"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "post": {
    "configSchema": {
      "description": "Configuration for HTTP actions with request bodies (POST, PUT, PATCH)",
      "type": "object",
      "properties": {
        "body": {
          "description": "Request payload as string or object (optional)",
          "type": [
            "string",
            "object"
          ],
          "title": "body"
        },
        "contentType": {
          "description": "Content-Type header override (default: 'application/json' if body is object, 'text/plain' if string)",
          "type": "string",
          "title": "contentType"
        },
        "url": {
          "description": "Target endpoint URL (supports template interpolation)",
          "type": "string",
          "title": "url"
        },
        "headers": {
          "description": "Request headers as key-value pairs (optional)",
          "type": "object",
          "title": "headers"
        },
        "timeout": {
          "description": "Request timeout in milliseconds (default: 30000)",
          "type": "number",
          "title": "timeout"
        },
        "retries": {
          "description": "Number of retry attempts on failure (default: 3)",
          "type": "number",
          "title": "retries"
        },
        "validateStatus": {
          "description": "Function to validate response status codes (default: status >= 200 && status < 300)",
          "type": "object",
          "title": "validateStatus"
        }
      },
      "required": [
        "url"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "patch": {
    "configSchema": {
      "description": "Configuration for HTTP actions with request bodies (POST, PUT, PATCH)",
      "type": "object",
      "properties": {
        "body": {
          "description": "Request payload as string or object (optional)",
          "type": [
            "string",
            "object"
          ],
          "title": "body"
        },
        "contentType": {
          "description": "Content-Type header override (default: 'application/json' if body is object, 'text/plain' if string)",
          "type": "string",
          "title": "contentType"
        },
        "url": {
          "description": "Target endpoint URL (supports template interpolation)",
          "type": "string",
          "title": "url"
        },
        "headers": {
          "description": "Request headers as key-value pairs (optional)",
          "type": "object",
          "title": "headers"
        },
        "timeout": {
          "description": "Request timeout in milliseconds (default: 30000)",
          "type": "number",
          "title": "timeout"
        },
        "retries": {
          "description": "Number of retry attempts on failure (default: 3)",
          "type": "number",
          "title": "retries"
        },
        "validateStatus": {
          "description": "Function to validate response status codes (default: status >= 200 && status < 300)",
          "type": "object",
          "title": "validateStatus"
        }
      },
      "required": [
        "url"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "get": {
    "configSchema": {
      "description": "Base configuration for all HTTP actions",
      "type": "object",
      "properties": {
        "url": {
          "description": "Target endpoint URL (supports template interpolation)",
          "type": "string",
          "title": "url"
        },
        "headers": {
          "description": "Request headers as key-value pairs (optional)",
          "type": "object",
          "title": "headers"
        },
        "timeout": {
          "description": "Request timeout in milliseconds (default: 30000)",
          "type": "number",
          "title": "timeout"
        },
        "retries": {
          "description": "Number of retry attempts on failure (default: 3)",
          "type": "number",
          "title": "retries"
        },
        "validateStatus": {
          "description": "Function to validate response status codes (default: status >= 200 && status < 300)",
          "type": "object",
          "title": "validateStatus"
        }
      },
      "required": [
        "url"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "base-http": {},
  "write": {
    "configSchema": {
      "description": "Configuration for file-write action",
      "type": "object",
      "properties": {
        "path": {
          "description": "File path to write (supports template interpolation)",
          "type": "string",
          "title": "path"
        },
        "content": {
          "description": "Content to write (supports template interpolation)",
          "type": "string",
          "title": "content"
        },
        "encoding": {
          "description": "File encoding (default: 'utf8')",
          "type": "string",
          "title": "encoding"
        },
        "frontMatter": {
          "description": "YAML front matter to prepend (only for .md files, optional)",
          "type": "object",
          "title": "frontMatter"
        },
        "replace": {
          "description": "Simple find/replace dictionary applied to content before writing (optional)",
          "type": "object",
          "title": "replace"
        }
      },
      "required": [
        "content",
        "path"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "read": {
    "configSchema": {
      "description": "Configuration for file-read action",
      "type": "object",
      "properties": {
        "path": {
          "description": "File path to read (supports template interpolation)",
          "type": "string",
          "title": "path"
        },
        "encoding": {
          "description": "File encoding (default: 'utf8')",
          "enum": [
            "ascii",
            "base64",
            "binary",
            "hex",
            "utf-8",
            "utf8"
          ],
          "type": "string",
          "title": "encoding"
        }
      },
      "required": [
        "path"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  }
};
