/**
 * Playbook provider initialization
 *
 * This module initializes all playbook providers by registering them with the
 * PlaybookProviderRegistry. Providers are registered in order, and the registry
 * uses first-match strategy during load().
 *
 * **Future**: This file will be generated by build-time code generation that scans
 * for provider modules. For now, it's manually maintained.
 *
 * @see {@link PlaybookProviderRegistry} Registry managing providers
 */

import { registerYamlProvider } from '../yaml/provider';

/**
 * Initialize all playbook providers
 *
 * Called by CLI entry points before any playbook loading occurs.
 * Registers all available playbook providers with the registry.
 *
 * **Registration Order**: Providers are registered in the order they appear below.
 * The registry uses first-match strategy, so order matters if multiple providers
 * support the same identifier pattern.
 *
 * @example
 * ```typescript
 * // In CLI entry point
 * import { initializeProviders } from '@catalyst/playbooks/registry/initialize-providers';
 *
 * async function main() {
 *   initializeProviders();
 *   // Now playbook loading works
 *   const playbook = await PlaybookProviderRegistry.getInstance().load('my-playbook');
 * }
 * ```
 */
export function initializeProviders(): void {
  // Register YAML provider
  registerYamlProvider();

  // Future: Load and register custom providers from config file
  // const config = loadCatalystConfig();
  // for (const providerModule of config.playbooks?.providers || []) {
  //   const { registerProvider } = await import(providerModule);
  //   registerProvider();
  // }
}
