/**
 * Index command implementation — generate .xe/features/README.md from spec frontmatter.
 *
 * @req FR:catalyst-cli/index.execute
 * @req FR:catalyst-cli/index.graceful
 * @req FR:catalyst-cli/index.gitignore
 * @req FR:feature-context/index.location
 * @req FR:feature-context/index.generated
 * @req FR:feature-context/index.content
 * @req FR:feature-context/index.generated-marker
 */

import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';
import { LogManager } from '../../core/logging';

const AUTO_GEN_MARKER =
  '<!-- AUTO-GENERATED by `catalyst index`. Do not edit by hand — update spec frontmatter and re-run. -->';

const MISSING_DESCRIPTION_PLACEHOLDER = '⚠️ missing description';

interface FeatureEntry {
  id: string;
  title: string;
  description: string;
  hasDescription: boolean;
}

/**
 * Execute the index command.
 *
 * Reads frontmatter (id, title, description) from every `.xe/features/{id}/spec.md`
 * and writes a sorted markdown table to `.xe/features/README.md`. Idempotent: re-running
 * with unchanged inputs produces no diff.
 *
 * Graceful on missing description: a warning is logged and the entry is emitted with a
 * placeholder. Enforcement of FR:spec.frontmatter.description is owned by traceability,
 * not this generator.
 *
 * Also ensures `.xe/features/.gitignore` excludes the generated README so it doesn't
 * drift in version control. The index is an AI-orientation artifact, not a reviewable
 * document; committing it creates diff noise and inevitable stale-commit drift.
 */
export async function indexCommand(): Promise<void> {
  const logger = LogManager.current();
  const cwd = process.cwd();
  const featuresDir = path.join(cwd, '.xe', 'features');
  const outputPath = path.join(featuresDir, 'README.md');

  if (!fs.existsSync(featuresDir)) {
    logger.error('CLI', 'Index', `No features directory at ${featuresDir}`);
    process.exit(1);
  }

  ensureGitignore(featuresDir, logger);

  const entries = collectEntries(featuresDir, logger);
  entries.sort((a, b) => a.id.localeCompare(b.id));

  const output = renderIndex(entries);

  const existing = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf-8') : '';
  if (existing === output) {
    logger.info('CLI', 'Index', `${outputPath} already current (${entries.length} features)`);
    return;
  }

  fs.writeFileSync(outputPath, output);
  logger.info('CLI', 'Index', `Wrote ${outputPath} (${entries.length} features)`);
}

/**
 * Idempotently ensure `.xe/features/.gitignore` ignores the generated README.
 *
 * - If the file did not exist, create it with `README.md` and `.gitignore` entries
 *   (the generated gitignore is also not meant to be committed).
 * - If the file existed, append `README.md` only if missing; do NOT self-add
 *   `.gitignore` — the user may have pre-existing rules they intend to commit.
 */
function ensureGitignore(
  featuresDir: string,
  logger: ReturnType<typeof LogManager.current>
): void {
  const gitignorePath = path.join(featuresDir, '.gitignore');
  const existed = fs.existsSync(gitignorePath);
  const existing = existed ? fs.readFileSync(gitignorePath, 'utf-8') : '';

  const linesSet = new Set(existing.split(/\r?\n/).map(l => l.trim()));
  const entriesToAdd: string[] = [];

  if (!linesSet.has('README.md')) entriesToAdd.push('README.md');

  // Only self-ignore when we're creating the file — respect user's existing file otherwise.
  if (!existed && !linesSet.has('.gitignore')) entriesToAdd.push('.gitignore');

  if (entriesToAdd.length === 0) return;

  const needsLeadingNewline = existing.length > 0 && !existing.endsWith('\n');
  const updated =
    existing + (needsLeadingNewline ? '\n' : '') + entriesToAdd.join('\n') + '\n';
  fs.writeFileSync(gitignorePath, updated);
  logger.info(
    'CLI',
    'Index',
    `Updated ${gitignorePath} with: ${entriesToAdd.join(', ')} (generated artifacts; not meant to be committed)`
  );
}

function collectEntries(
  featuresDir: string,
  logger: ReturnType<typeof LogManager.current>
): FeatureEntry[] {
  const entries: FeatureEntry[] = [];

  for (const dirent of fs.readdirSync(featuresDir, { withFileTypes: true })) {
    if (!dirent.isDirectory()) continue;

    const specPath = path.join(featuresDir, dirent.name, 'spec.md');
    if (!fs.existsSync(specPath)) continue;

    const fm = readFrontmatter(specPath);
    if (!fm) {
      logger.warning('CLI', 'Index', `${specPath}: missing or invalid frontmatter — skipping`);
      continue;
    }

    const id = typeof fm.id === 'string' ? fm.id : dirent.name;
    const title = typeof fm.title === 'string' ? fm.title : id;
    const rawDescription = typeof fm.description === 'string' ? fm.description.trim() : '';
    const hasDescription = rawDescription.length > 0;

    if (!hasDescription) {
      logger.warning(
        'CLI',
        'Index',
        `${specPath}: missing required 'description' frontmatter field (see FR:feature-context/spec.frontmatter.description)`
      );
    }

    entries.push({
      id,
      title,
      description: hasDescription ? rawDescription : MISSING_DESCRIPTION_PLACEHOLDER,
      hasDescription,
    });
  }

  return entries;
}

function readFrontmatter(filePath: string): Record<string, unknown> | null {
  const content = fs.readFileSync(filePath, 'utf-8');
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return null;
  try {
    const parsed = yaml.load(match[1], { schema: yaml.JSON_SCHEMA });
    return parsed && typeof parsed === 'object' ? (parsed as Record<string, unknown>) : null;
  } catch {
    return null;
  }
}

function renderIndex(entries: FeatureEntry[]): string {
  const missingCount = entries.filter(e => !e.hasDescription).length;
  const lines: string[] = [
    AUTO_GEN_MARKER,
    '',
    '# Features',
    '',
    'At-a-glance index of every feature in this project.',
    '',
  ];

  if (missingCount > 0) {
    lines.push(
      `> ⚠️ ${missingCount} feature${missingCount === 1 ? '' : 's'} missing \`description\` frontmatter. Run \`catalyst traceability\` to enforce.`
    );
    lines.push('');
  }

  lines.push('| Feature | Title | Description |');
  lines.push('| --- | --- | --- |');

  for (const entry of entries) {
    const link = `[${entry.id}](${entry.id}/spec.md)`;
    lines.push(`| ${link} | ${entry.title} | ${entry.description} |`);
  }

  lines.push('');
  return lines.join('\n');
}
